service: autotag-api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-localstack

custom:
  stage: ${opt:stage, 'local'}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  localstack:
    host: http://localhost
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      SQS: http://localhost:4576
      Lambda: http://localhost:4574

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem

resources:
  - ${file(resources/dynamodb-table.yml)}

functions:
  projectCreate:
    handler: src/project.create
    events:
      - http:
          path: project
          method: post
          cors: true
          authorizer: aws_iam

  projectGet:
    handler: src/project.get
    events:
      - http:
          path: project/{id}
          method: get
          cors: true
          authorizer: aws_iam

  projectList:
    handler: src/project.list
    events:
      - http:
          path: project
          method: get
          cors: true
          authorizer: aws_iam

  resourceAdd:
    handler: src/resource.add
    events:
      - s3:
          bucket: autotag-${opt:stage, 'local'}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/

