service: autotag-api

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem

functions:
  projectCreate:
    handler: src/project.create
    events:
      - http:
          path: success
          method: post
          cors: true
          authorizer: aws_iam
