Resources:
  ResourcesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: auto-tag-${self:custom.stage}-resources
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: resourceId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: resourceId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

