Resources:
  ResourcesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: autotag-resources-${self:custom.stage}
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: resourceId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: resourceId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

